ecomapp/urls.py
from django.urls import path
from .views import *


app_name = "ecomapp"
urlpatterns = [

    # Client side pages
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact-us/", ContactView.as_view(), name="contact"),
    path("all-products/<slug:slug>/", AllProductsView.as_view(), name="allproducts"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="productdetail"),

    path("add-to-cart/<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("customer-checkout-view/", CheckoutView.as_view(), name="checkout"),

    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),

    path("esewa-request/", EsewaRequestView.as_view(), name="esewarequest"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),

    path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),

    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),

    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),

    path("search/", SearchView.as_view(), name="search"),

    path("forgot-password/", PasswordForgotView.as_view(), name="passworforgot"),
    path("password-reset/<email>/<token>/",
         PasswordResetView.as_view(), name="passwordreset"),
    # Admin Side pages

    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(),
         name="adminorderdetail"),

    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),

    path("admin-order-<int:pk>-change/",
         AdminOrderStatuChangeView.as_view(), name="adminorderstatuschange"),

    path("admin-product/list/", AdminProductListView.as_view(),
         name="adminproductlist"),
    path("admin-product/add/", AdminProductCreateView.as_view(),
         name="adminproductcreate"),
     path('faq/', faqview.as_view(), name='faq'),


]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ecomapp.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


class ShippingDetail(models.Model):
    fname = models.CharField(max_length=255, null=True, blank=True)
    lname = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    country = models.CharField(max_length=255, null=True, blank=True)
    street_address = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=255, null=True, blank=True)
    state = models.CharField(max_length=255, null=True, blank=True)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("Khalti", "Khalti"),
    ("Esewa", "Esewa"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=255, null=True, blank=True)
    mobile = models.CharField(max_length=255, null=True, blank=True)
    shipping_address = models.TextField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)
    order_note = models.TextField(null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)

class Slider(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    subtitle = models.CharField(max_length=255, null=True, blank=True)
    price = models.CharField(max_length=255, null=True, blank=True)
    product_url = models.URLField(max_length=255, null=True, blank=True)
    image = models.ImageField(upload_to="sliders")


class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    subject = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.subject)

templates/includes/footer.html
<!--footer area start-->
<footer class="footer_widgets footer_three">
    <div class="container">
        <div class="footer_top">
            <div class="row">
                <div class="col-lg-4 col-md-4">
                    <div class="widgets_container contact_us">
                        <a href="index.html"><img src="assets/img/logo/pc-builder-logo.png" alt=""></a>
                        <div class="footer_contact">
                            <ul>
                                <li><i class="zmdi zmdi-home"></i><span>Addresss:</span> Kirtipur Ring Rd,
                                    Kathmandu,
                                    Nepal</li>
                                <li><i class="zmdi zmdi-phone-setting"></i><span>Phone:</span><a
                                        href="tel:(+1) 866-540-3229">(+977) 866-540-3229</a> </li>
                                <li><i class="zmdi zmdi-email"></i><span>Email:</span> info@pcbuild.com</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">
                    <div class="widgets_container widget_menu">
                        <h3>CUSTOMER SERVICE</h3>
                        <div class="footer_menu">
                            <ul>
                                
                                <li><a href="{% url 'ecomapp:contact'%}"> Contact</a></li>

                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">
                    <div class="widgets_container widget_menu">
                        <h3>Quick Links</h3>
                        <div class="footer_menu">
                            <ul>
                                <li><a href="{% url 'ecomapp:about'%}">About Us</a></li>
                                
                                <li><a href="{%url 'ecomapp:faq'%}"> Frequently Questions</a></li>

                            </ul>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer_bottom">
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="col-lg-12 col-md-12">
                    <div class="copyright_area">
                        <p>Copyright &copy; 2023 <a href="#"> PC Build </a> All Right Reserved.</p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</footer>
<!--footer area end-->

templates/includes/header.html
{% load static %}
<!--header area start-->
<header class="header_area header_color">
    <!--header top start-->
    <div class="header_top">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4">
                    <div class="welcome_text">
                        <p>Welcome to <span>PC Build</span> </p>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="top_right text-right">
                        {% if request.user.customer %}
                        <ul>
                            <li class="top_links"><a href="#"><i class="zmdi zmdi-account"></i> My account <i
                                        class="zmdi zmdi-caret-down"></i></a>
                                <ul class="dropdown_links">
                                    <li><a href="{% url 'ecomapp:customerprofile' %}">My Account </a></li>
                                    <li><a href="{% url 'ecomapp:mycart' %}">Shopping Cart</a></li>
                                    <li><a href="{% url 'ecomapp:customerlogout' %}">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                        {% else %}
                        <ul>
                            <li class="top_links"><a href="#"><i class="zmdi zmdi-account"></i> My Account <i
                                class="zmdi zmdi-caret-down"></i></a>
                                <ul class="dropdown_links">
                                    <li><a href="{% url 'ecomapp:customerlogin' %}">Login</a></li>
                                    <li><a href="{% url 'ecomapp:customerregistration' %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">Register</a></li>
                                </ul>
                            </li>
                        </ul>
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!--header top start-->
    <!--header center area start-->
    <div class="header_middle">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-3 col-md-12 col-xs-12">
                    <div class="logo align-items-center">
                        <a href="{% url 'ecomapp:home' %}"><img src="{% static 'img/logo/pc-builder-logo.png' %}" alt="logo"></a>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="header_middle_inner">
                        <div class="search-container">
                            <form action="{% url 'ecomapp:search' %}" method="get">
                                <div class="hover_category">
                                    <select class="select_option" name="select" id="categori">
                                        <option selected value="1">All Categories</option>
                                        {% for cat in header_categories %}
                                        <option value="{{ cat.id }}">{{ cat.title }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="search_box">
                                    <input placeholder="Search product..." type="text" name="keyword">
                                    <button type="submit"><i class="zmdi zmdi-search"></i></button>
                                </div>
                            </form>
                        </div>
                        <!-- cart start -->
                        <div class="mini_cart_wrapper">
                            <a href="javascript:void(0)"><i class="zmdi zmdi-shopping-basket"></i> <span>{{ cart.cartproduct_set.all|length }} items - {{cart.total}}
                               </span> </a>
                            <!--mini cart-->
                            <div class="mini_cart">
                                {% for item in cart.cartproduct_set.all %}
                                <div class="cart_item">
                                    <div class="cart_img">
                                        <a href="#"><img src="{{item.product.image.url}}" alt=""></a>
                                    </div>
                                    <div class="cart_info">
                                        <a href="#">{{ item.product.title }}</a>

                                        <span class="quantity">Qty: {{ item.quantity }}</span>
                                        <span class="price_cart">Rs.{{ item.rate }}</span>

                                    </div>
                                    <div class="cart_remove">
                                        <a href="#"><i class="ion-android-close"></i></a>
                                    </div>
                                </div>
                                {% endfor %}
                                

                                <div class="mini_cart_footer">
                                    <div class="cart_button">
                                        <a href="{% url 'ecomapp:mycart' %}">View cart</a>
                                        {% if cart.cartproduct_set.all %}
                                        <a href="{% url 'ecomapp:checkout' %}">Checkout</a>
                                        {% endif %}
                                    </div>
                                </div>

                            </div>
                            <!--mini cart end-->
                        </div>
                        <!-- cart end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--header center area end-->

    <!--header middel start-->
    <div class="header_bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-3">
                    <div class="categories_menu categori_three">
                        <div class="categories_title">
                            <h2 class="categori_toggle">Categories</h2>
                        </div>
                        <div class="categories_menu_toggle">
                            <ul>
                                {% for cat in header_categories %}
                                <li><a href="{% url 'ecomapp:allproducts' cat.slug %}"><span></span> {{ cat.title }}<i
                                            class="fa fa-angle-right"></i></a>

                                </li>
                                {% endfor %}

                                
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="main_menu menu_three header_position">
                        <nav>
                            <ul>
                                <li class="active"><a href="{% url 'ecomapp:home' %}"><i class="zmdi zmdi-home"></i> home </i></a>

                                </li>

                                <li><a href="{% url 'ecomapp:faq' %}"><i class="zmdi zmdi-star"></i> FAQ </a>

                                </li>

                                <li><a href="{% url 'ecomapp:about' %}"><i class="zmdi zmdi-comments"></i> about Us</a></li>
                                <li><a href="{% url 'ecomapp:contact' %}"><i class="zmdi zmdi-account-box-mail"></i> Contact Us</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--header middel end-->

</header>
<!--header area end-->

templates/includes/mobile_header.html
 <!--Offcanvas resposnsive (mobile) menu area start-->

 <div class="Offcanvas_menu">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="canvas_open">
                    <span>MENU</span>
                    <a href="javascript:void(0)"><i class="ion-navicon"></i></a>
                </div>
                <div class="Offcanvas_menu_wrapper">
                    <div class="canvas_close">
                        <a href="javascript:void(0)"><i class="ion-android-close"></i></a>
                    </div>
                    <div class="welcome_text">
                        <p>Welcome to <span>PC Build</span> </p>
                    </div>

                    <div class="top_right">
                        <ul>
                            <li class="top_links"><a href="#"><i class="zmdi zmdi-account"></i> My account <i
                                        class="zmdi zmdi-caret-down"></i></a>
                                <ul class="dropdown_links">
                                    <li><a href="{% url 'ecomapp:customerprofile' %}">My Account </a></li>
                                    <li><a href="{% url 'ecomapp:mycart' %}">Shopping Cart</a></li>
                                    <li><a href="{% url 'ecomapp:customerlogout' %}">Logout</a></li>
                                </ul>
                            </li>

                        </ul>
                    </div>
                    <div class="search-container">
                        <form action="{% url 'ecomapp:search' %}" method="get">
                            <div class="hover_category">
                                <select class="select_option" name="select" id="categori">
                                    <option selected value="1">All Categories</option>
                                    {% for cat in header_categories %}
                                    <option value="{{ cat.id }}">{{ cat.title }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="search_box">
                                <input placeholder="Search product..." type="text" name="keyword">
                                <button type="submit"><i class="zmdi zmdi-search"></i></button>
                            </div>
                        </form>
                    </div>
                    <div class="mini_cart_wrapper">
                        <a href="javascript:void(0)"><i class="zmdi zmdi-shopping-basket"></i> <span>{{ cart.cartproduct_set.all|length }} items -
                                Rs.{{cart.total}}</span> </a>
                        <!--mini cart-->
                        <div class="mini_cart">
                            {% for item in cart.cartproduct_set.all %}
                            <div class="cart_item">
                                <div class="cart_img">
                                    <a href="#"><img src="{{item.product.image.url}}" alt=""></a>
                                </div>
                                <div class="cart_info">
                                    <a href="#">{{ item.product.title }}</a>

                                    <span class="quantity">Qty: {{ item.quantity }}</span>
                                    <span class="price_cart">Rs.{{ item.rate }}</span>

                                </div>
                                <div class="cart_remove">
                                    <a href="#"><i class="ion-android-close"></i></a>
                                </div>
                            </div>
                            {% endfor %}
                            
                            <div class="mini_cart_table">
                                <div class="cart_total">
                                    <span>Subtotal:</span>
                                    <span class="price">Rs.{{cart.total}}</span>
                                </div>
                            </div>

                            <div class="mini_cart_footer">
                                <div class="cart_button">
                                    <a href="{% url 'ecomapp:mycart' %}">View cart</a>
                                </div>
                            </div>

                        </div>
                        <!--mini cart end-->
                    </div>
                    <div id="menu" class="text-left ">
                        <ul class="offcanvas_main_menu">
                            <li class="menu-item-has-children active">
                                <a href="{% url 'ecomapp:home' %}">Home</a>

                            </li>
                            <li class="menu-item-has-children">
                                <a href="faq.html">FAQ</a>
                            </li>
                            <li class="menu-item-has-children">
                                <a href="about.html">about Us</a>
                            </li>
                            <li class="menu-item-has-children">
                                <a href="contact.html"> Contact Us</a>
                            </li>
                        </ul>
                    </div>

                    <div class="Offcanvas_footer">
                        <span><a href="#"><i class="fa fa-envelope-o"></i> info@pcbuild.com</a></span>
                        <ul>
                            <li class="facebook"><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li class="twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li class="pinterest"><a href="#"><i class="fa fa-pinterest-p"></i></a></li>
                            <li class="google-plus"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li class="linkedin"><a href="#"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Offcanvas mobile menu area end-->