ecomapp/urls.py
from django.urls import path
from .views import *


app_name = "ecomapp"
urlpatterns = [

    # Client side pages
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact-us/", ContactView.as_view(), name="contact"),
    path("all-products/<slug:slug>/", AllProductsView.as_view(), name="allproducts"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="productdetail"),

    path("add-to-cart/<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("customer-checkout-view/", CheckoutView.as_view(), name="checkout"),

    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),

    path("esewa-request/", EsewaRequestView.as_view(), name="esewarequest"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),

    path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),

    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),

    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),

    path("search/", SearchView.as_view(), name="search"),

    path("forgot-password/", PasswordForgotView.as_view(), name="passworforgot"),
    path("password-reset/<email>/<token>/",
         PasswordResetView.as_view(), name="passwordreset"),
    # Admin Side pages

    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(),
         name="adminorderdetail"),

    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),

    path("admin-order-<int:pk>-change/",
         AdminOrderStatuChangeView.as_view(), name="adminorderstatuschange"),

    path("admin-product/list/", AdminProductListView.as_view(),
         name="adminproductlist"),
    path("admin-product/add/", AdminProductCreateView.as_view(),
         name="adminproductcreate"),
     path('faq/', faqview.as_view(), name='faq'),


]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ecomapp.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


class ShippingDetail(models.Model):
    fname = models.CharField(max_length=255, null=True, blank=True)
    lname = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    country = models.CharField(max_length=255, null=True, blank=True)
    street_address = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=255, null=True, blank=True)
    state = models.CharField(max_length=255, null=True, blank=True)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("Khalti", "Khalti"),
    ("Esewa", "Esewa"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=255, null=True, blank=True)
    mobile = models.CharField(max_length=255, null=True, blank=True)
    shipping_address = models.TextField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)
    order_note = models.TextField(null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)

class Slider(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    subtitle = models.CharField(max_length=255, null=True, blank=True)
    price = models.CharField(max_length=255, null=True, blank=True)
    product_url = models.URLField(max_length=255, null=True, blank=True)
    image = models.ImageField(upload_to="sliders")


class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    subject = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.subject)

templates/addtocart.html
{% extends 'base.html' %}

{% block title %}Add to cart{% endblock %}

{% block content %}
<div class="container">
    <h3>Product added to cart successfully.</h3>
</div>
{% endblock %}

templates/contactus.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Contact us{% endblock %}

{% block content %}
   <!--breadcrumbs area start-->
   <div class="breadcrumbs_area">
    <div class="container">   
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <ul>
                        <li><a href="{% url 'ecomapp:home'%}">home</a></li>
                        <li>Contact us</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>         
</div>
<!--breadcrumbs area end-->

 <!--contact map start-->
<div class="contact_map mt-60">
   <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="mapouter"><div class="gmap_canvas"><iframe class="gmap_iframe" width="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=1025&amp;height=400&amp;hl=en&amp;q=kirtippur,nayabazar&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe><a href="https://pdflist.com/" alt="pdf download">Pdf download</a></div><style>.mapouter{position:relative;text-align:right;width:100%;height:400px;}.gmap_canvas {overflow:hidden;background:none!important;width:100%;height:400px;}.gmap_iframe {height:400px!important;}</style></div>
            </div>
        </div>
    </div>
</div>
<!--contact map end-->

<!--contact area start-->
<div class="contact_area">
    <div class="container">   
        <div class="row">
            <div class="col-lg-6 col-md-12">
               <div class="contact_message content">
                    <h3>contact us</h3>    
                     <p>Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram anteposuerit litterarum formas human. qui sequitur mutationem consuetudium lectorum. Mirum est notare</p>
                    <ul>
                        <li><i class="fa fa-fax"></i>  Address : Kirtipur ring road ,KTM City</li>
                        <li><i class="fa fa-phone"></i> <a href="#">Info@pcbuild.com</a></li>
                        <li><i class="fa fa-envelope-o"></i> (+977)8888888888</li>
                    </ul>             
                </div> 
            </div>
            <div class="col-lg-6 col-md-12">
               <div class="contact_message form">
                    <h3>Place your Requirement</h3>   
                    <form id="" method="POST">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit"> Send</button>  
                        <p class="form-messege"></p>
                    </form> 

                </div> 
            </div>
        </div>
    </div>    
</div>

<!--contact area end-->

<!--brand newsletter area start-->
<div class="brand_newsletter_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="brand_container owl-carousel">
                    <div class="single_brand">
                        <a href="#"><img src="{% static 'img/brand/brand.png' %}" alt=""></a>
                    </div>
                    <div class="single_brand">
                        <a href="#"><img src="{% static 'img/brand/brand1.png' %}" alt=""></a>
                    </div>
                    <div class="single_brand">
                        <a href="#"><img src="{% static 'img/brand/brand2.png' %}" alt=""></a>
                    </div>
                    <div class="single_brand">
                        <a href="#"><img src="{% static 'img/brand/brand3.png' %}" alt=""></a>
                    </div>
                    <div class="single_brand">
                        <a href="#"><img src="{% static 'img/brand/brand4.png' %}" alt=""></a>
                    </div>
                    <div class="single_brand">
                        <a href="#"><img src="{% static 'img/brand/brand5.png' %}" alt=""></a>
                    </div>
                    <div class="single_brand">
                        <a href="#"><img src="{% static 'img/brand/brand6.png' %}" alt=""></a>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>
<!--brand area end-->
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Welcome to PC Build {% endblock %}
{% block content %}
<!--slider area start-->
<section class="slider_section mb-50">
    <div class="container-fluid">
        <div class="row no-gutters">
            <div class="col-12">
                <div class="slider_area slider_three owl-carousel">
                    {% for slider in banners %}
                    <div class="single_slider d-flex align-items-center" data-bgimg="{{slider.image.url}}">
                        <div class="slider_content slider_content_three content_position_center">
                            <h1 color='white'>{{slider.title}}</span></h1>
                            <span>{{slider.subtitle}}</span>
                            <h2><span>Rs.</span> {{slider.price}} <span>0</span></h2>
                            <a href="{{slider.product_url}}">shop now</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

</section>
<!--slider area end-->

<!--shipping area start-->
<div class="shipping_area_two mb-50">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="single_shipping_box">
                    <div class="shipping_box_icone">
                        <i class="zmdi zmdi-local-shipping zmdi-hc-fw"></i>
                    </div>
                    <div class="shipping_box_content">
                        <h3>Free Shipping</h3>
                        <p>On Orders Over Rs.99</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single_shipping_box">
                    <div class="shipping_box_icone">
                        <i class="zmdi zmdi-replay-5"></i>
                    </div>
                    <div class="shipping_box_content">
                        <h3>30 – Day Returns</h3>
                        <p>Moneyback Guarantee</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single_shipping_box">
                    <div class="shipping_box_icone">
                        <i class="zmdi zmdi-phone-in-talk"></i>
                    </div>
                    <div class="shipping_box_content">
                        <h3>24/7 Support Online</h3>
                        <p>Consultations</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single_shipping_box">
                    <div class="shipping_box_icone">
                        <i class="zmdi zmdi-run"></i>
                    </div>
                    <div class="shipping_box_content">
                        <h3>99% Customer</h3>
                        <p>Feedbacks</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--shipping area end-->

<!--home product area start-->
<section class="home_product_area home_product_three mb-50">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="product_header">
                    <div class="section_title section_title_two">
                        <h2>Computers & Accessories</h2>
                    </div>
                    <div class="product_tab_button">
                        <ul class="nav" role="tablist">
                            {% for cat in home_categories %}
                            <li>
                                <a {% if forloop.first %}class="active"{% endif %} data-bs-toggle="tab" href="#cat-{{cat.id}}" role="tab"
                                    aria-controls="cat-{{cat.id}}" aria-selected="true">
                                    {{cat.title}}
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="tab-content">
                    <!-- cpu -->
                    {% for cat in home_categories %}
                    <div {% if forloop.first %}class="tab-pane fade show active"{% endif %} class="tab-pane fade" id="cat-{{cat.id}}" role="tabpanel">
                        <div class="product_carousel product_column4 owl-carousel">
                            {% for p in cat.product_set.all %}
                            <div class="single_product">
                                <div class="product_thumb">
                                    <a href="{% url 'ecomapp:productdetail' p.slug %}"><img src="{{p.image.url}}"
                                            alt="{{p.title}}" style="height:215px"></a>
                                    <div class="quick_button">
                                        <a href="{% url 'ecomapp:productdetail' p.slug %}" 
                                            title="quick view"> <i class="zmdi zmdi-eye"></i></a>
                                    </div>
                                </div>
                                <div class="product_content">
                                    <div class="product_name">
                                        <h3><a href="{% url 'ecomapp:productdetail' p.slug %}">{{p.title}}</a></h3>
                                        
                                    </div>
                                    
                                    <div class="price_box">
                                        <span class="current_price">Rs.{{p.selling_price}}</span>
                                        <span class="old_price">Rs. {{p.marked_price}}</span>
                                    </div>
                                    <div class="action_links">
                                        <ul>
                                            
                                            <li class="add_to_cart"><a href="{% url 'ecomapp:addtocart' pro_id=p.id %}" title="add to cart"><i
                                                        class="zmdi zmdi-shopping-cart-plus"></i> add to cart</a>
                                            </li>
                                            
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                   
                </div>

            </div>
        </div>
    </div>
</section>
<!--home product area end-->

<!--banner area start-->
<div class="banner_area banner_three mb-50">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="single_banner">
                    <div class="banner_thumb">
                        <a href="shop.html"><img src="{% static 'img/bg/banner4.jpg' %}" alt=""></a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<!--banner area end-->

<!--brand newsletter area start-->
<div class="brand_newsletter_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="brand_container owl-carousel">
                    <div class="single_brand">
                        <a href="#"><img src="{% static 'img/brand/brand.png' %}" alt=""></a>
                    </div>
                    <div class="single_brand">
                        <a href="#"><img src="{% static 'img/brand/brand1.png' %}" alt=""></a>
                    </div>
                    <div class="single_brand">
                        <a href="#"><img src="{% static 'img/brand/brand2.png' %}" alt=""></a>
                    </div>
                    <div class="single_brand">
                        <a href="#"><img src="{% static 'img/brand/brand3.png' %}" alt=""></a>
                    </div>
                    <div class="single_brand">
                        <a href="#"><img src="{% static 'img/brand/brand4.png' %}" alt=""></a>
                    </div>
                    <div class="single_brand">
                        <a href="#"><img src="{% static 'img/brand/brand5.png' %}" alt=""></a>
                    </div>
                    <div class="single_brand">
                        <a href="#"><img src="{% static 'img/brand/brand6.png' %}" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--brand area end-->

{% endblock %}

templates/mycart.html
{% extends 'base.html' %}
{% load static %}


{% block title %} My cart{% endblock %}


{% block content %}
    <!--breadcrumbs area start-->
    <div class="breadcrumbs_area">
        <div class="container">   
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumb_content">
                        <ul>
                            <li><a href="">home</a></li>
                            <li>Shopping Cart</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>         
    </div>
    <!--breadcrumbs area end-->
    
     <!--shopping cart area start -->
    <div class="shopping_cart_area mt-60">
        <div class="container">  
            <form action="#"> 
                <div class="row">
                    <div class="col-12">
                        <div class="table_desc">
                            <div class="cart_page table-responsive">
                                <table>
                            <thead>
                                <tr>
                                    <th class="product_thumb">Image</th>
                                    <th class="product_name">Product</th>
                                    <th class="product-price">Price</th>
                                    <th class="product_quantity">Quantity</th>
                                    <th class="product_total">Total</th>
                                    <th class="product_remove">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cp in cart.cartproduct_set.all %}
                                <tr>
                                    <td class="product_thumb"><a href="#"><img src="{{cp.product.image.url}}" alt=""></a></td>
                                    <td class="product_name"><a href="#">{{cp.product.title}}</a></td>
                                    <td class="product-price">Rs. {{ cp.rate }}</td>
                                    <td class="product_quantity"><label>Quantity</label>
                                        {{cp.quantity}}
                                    </td>
                                    <td class="product_total">Rs. {{cp.subtotal}}</td>
                                    <td class="product_remove">
                                        <a href="{% url 'ecomapp:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                                        <a href="{% url 'ecomapp:managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                                        <a href="{% url 'ecomapp:managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
                                    </td>
                                </tr>
                                {% endfor %}
                                
                                

                            </tbody>

                        </table>   
                            </div> 
                            {% if cart.cartproduct_set.all %} 
                            <div class="cart_submit">
                                <a id="update-cart" href="{% url 'ecomapp:emptycart' %}">Empty cart</a>
                            </div>
                            {% endif %}
                        </form>
      
                        </div>
                     </div>
                 </div>
                 <!--coupon code area start-->
                <div class="coupon_area">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="coupon_code right">
                                <h3>Cart Totals</h3>
                                <div class="coupon_inner">
                                   <div class="cart_subtotal">
                                       <p>Subtotal</p>
                                       <p class="cart_amount">Rs. {{cart.total}}</p>
                                   </div>
                                   <div class="cart_subtotal">
                                       <p>Shipping</p>
                                       <p class="cart_amount"> Rs. 0.00</p>
                                   </div>
                                   <a href="#">Calculate shipping</a>

                                   <div class="cart_subtotal">
                                       <p>Total</p>
                                       <p class="cart_amount">Rs. {{cart.total}}</p>
                                   </div>
                                   {% if cart.cartproduct_set.all %}
                                   <div class="checkout_btn">
                                       <a href="{% url 'ecomapp:checkout' %}">Proceed to Checkout</a>
                                   </div>
                                   {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--coupon code area end-->
            </form> 
        </div>     
    </div>
     <!--shopping cart area end -->
    

{% endblock %}

{% block js %}

    <script>
        // $(document).ready(function(){
        //     $('#update-cart').on('click', function(){
        //         $('#quantity-update').submit();
        //     });
        // });
    </script>

{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% block title %}Search {% endblock %}

{% block content %}
 <!--breadcrumbs area start-->
 <div class="breadcrumbs_area">
    <div class="container">   
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <ul>
                        <li><a href="">home</a></li>
                        <li>{{request.GET.keyword}} </li>
                        <li>All Results:</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>         
</div>
<!--breadcrumbs area end-->

<!--shop  area start-->
<div class="shop_area shop_reverse mt-50 mb-50">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-12">
               <!--sidebar widget start-->
                <aside class="sidebar_widget">
                    <div class="shop_sidebar_banner mb-50">
                        <a href="#"><img src="assets/img/bg/banner16.jpg" alt=""></a>
                    </div>
                    <div class="widget_list widget_categories">
                        <h2>categories</h2>
                        <ul>
                            {% for cat in header_categories %}
                            <li>
                                <a href="{% url 'ecomapp:allproducts' cat.slug %}">{{ cat.title }}</a> 
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                   
                </aside>
                <!--sidebar widget end-->
            </div>
            <div class="col-lg-9 col-md-12">
                <!--shop wrapper start-->
                <!--shop toolbar start-->                    
                <div class="shop_title">
                    <h1>{{request.GET.keyword}}</h1>
                </div>
                <div class="shop_toolbar_wrapper">
                    <div class="shop_toolbar_btn">

                        <button data-role="grid_3" type="button" class="active btn-grid-3" data-bs-toggle="tooltip" title="3"></button>

                        <button data-role="grid_4" type="button"  class=" btn-grid-4" data-bs-toggle="tooltip" title="4"></button>

                        <button data-role="grid_list" type="button"  class="btn-list" data-bs-toggle="tooltip" title="List"></button>
                    </div>
                    
                    
                </div>
                <!--shop toolbar end-->
                 <div class="row no-gutters shop_wrapper">
                    {% for p in results %}
                    <div class="col-lg-4 col-md-4 col-12 ">
                    <div class="single_product">
                        <div class="product_thumb">
                            <a href="{% url 'ecomapp:productdetail' p.slug %}"><img src="{{p.image.url}}"
                                    alt="{{p.title}}" style="max-width: 240px, height:215px;"></a>
                            <div class="quick_button">
                                <a href="{% url 'ecomapp:productdetail' p.slug %}" data-bs-toggle="modal" data-bs-target="#modal_box"
                                    title="quick view"> <i class="zmdi zmdi-eye"></i></a>
                            </div>
                        </div>
                        <div class="product_content">
                            <div class="product_name">
                                <h3><a href="{% url 'ecomapp:productdetail' p.slug %}">{{p.title}}</a></h3>
                                
                            </div>
                            <div class="price_box">
                                <span class="current_price">Rs.{{p.selling_price}}</span>
                                <span class="old_price">Rs. {{p.marked_price}}</span>
                            </div>
                            <div class="action_links">
                                <ul>
                                    
                                    <li class="add_to_cart"><a href="{% url 'ecomapp:addtocart' pro_id=p.id %}" title="add to cart"><i
                                                class="zmdi zmdi-shopping-cart-plus"></i> add to cart</a>
                                    </li>
                                    
                                </ul>
                            </div>
                        </div>
                    </div>
                    </div>
                    
                    {% endfor %}
                   
                                   
                
                <!--shop toolbar end-->
                <!--shop wrapper end-->
            </div>
        </div>
    </div>
</div>
<!--shop  area end-->

{% endblock %}